/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hteng_ndk_hello_HelloManager */

#ifndef _Included_com_hteng_ndk_hello_HelloManager
#define _Included_com_hteng_ndk_hello_HelloManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hteng_ndk_hello_HelloManager
 * Method:    getHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hteng_ndk_hello_HelloManager_getHelloString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
